#!/bin/sh -e

IFACE="$1"
REMOTE="<<Gateway LAN IP>>"

case "$5" in
    $REMOTE)
        iptables -t nat -C POSTROUTING -o $IFACE -j MASQUERADE && exit 0
        iptables -t nat -A POSTROUTING -o $IFACE -j MASQUERADE
    ;;
    *)
esac

exit 0
